---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: blue95
description: A desktop for your childhood home's computer room

base-image: quay.io/fedora-ostree-desktops/xfce-atomic
image-version: 41

# module configuration, executed in order
modules:
  - type: containerfile
    containerfiles: ["ublue"]

  - type: bling
    install:
      - ublue-update

  - type: rpm-ostree
    install:
      - btop
      - catfish
      - fastfetch
      - gdb
      - libcanberra
      - libcanberra-gtk3
      - lightdm-gtk-greeter-settings
      - mate-disk-usage-analyzer
      - mate-system-monitor
      - menulibre
      - neovim
      - orage
      - python3-cairosvg
      - plymouth-plugin-script
      - qt5ct
      - qt5-qtstyleplugins
      - sox
      - strace
      - vorbis-tools
      - wine-ms-sans-serif-fonts
      - wine-tahoma-fonts
      - xscreensaver-extras
      - xscreensaver-extras-gss
    remove:
      - firefox
      - firefox-langpacks

  - type: files
    files:
      - source: system
        destination: /


  - type: script
    scripts:
      - 00-image-info.sh
      - 02-defaults.sh
      - 03-ublue.sh
      - 10-install-appimages.sh
      - 11-xfce-extras.sh
      - 20-chicago95.sh
      - 21-de-tweaks.sh

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished
    system:
      # Flathub will be used by default
      install:
        - org.mozilla.firefox
        - org.kde.kolourpaint
        - org.dupot.easyflatpak

  # Regenerate initramfs because of plymouth
  - type: initramfs

  - type: signing

